server:
  port: 8001


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbCliente
    username: root
    password:
  jpa:
    hibernate:
    ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
      
