server:
  port: 8081
  
spring:
  cloud:
    config:
      server:
        git:
          default-label: multi
          uri: https://github.com/lgonzalez3004/micro-servicio
          search-paths: config-data
  application:
    name: config-service
    
          

